default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
        exclude: cookiecutter/
      - id: check-builtin-literals
        exclude: cookiecutter/
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/asottile/pyupgrade
    rev: a25bb536e10881d928ee824910cbaab8f4719bd1  # frozen: v3.17.0
    hooks:
    - id: pyupgrade
      args: [--py311-plus, --keep-runtime-typing]
  - repo: https://github.com/myint/autoflake
    rev: '0544741e2b4a22b472d9d93e37d4ea9153820bb1'  # frozen: v2.3.1
    hooks:
      - id: autoflake
        exclude: cookiecutter/
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variables ]
        verbose: true
  - repo: https://github.com/bwhmather/ssort
    rev: '202524364c6ba81752b4fa9c77f16c9ccd5a5e28'  # frozen: 0.13.0
    hooks:
      - id: ssort
        exclude: cookiecutter/
  - repo: https://github.com/pycqa/isort
    rev: 'c235f5e450b4b84e58d114ed4c589cbf454175a3'  # frozen: 5.13.2
    hooks:
      - id: isort
        exclude: cookiecutter/
        args: ["--profile", "black", "--line-length", "120"]
  - repo: https://github.com/pycqa/flake8
    rev: 'e43806be3607110919eff72939fda031776e885a'  # frozen: 7.1.1
    hooks:
      - id: flake8
        exclude: cookiecutter/
        args: ["--max-line-length=120"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "f7aa1f9a50202a2cd7cef269f8d83f5ac91b2915"  # frozen: 24.8.0
    hooks:
      - id: black
        exclude: cookiecutter/
        args: ["--line-length", "120"]
  - repo: local
    hooks:
    - id: check-bash-syntax
      name: Check shell scripts syntax correctness
      language: system
      entry: bash -n
      files: \.sh$
